### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by benswift** [cinquemb/WienerFilter#1]
Hi there, what's the licence for this code?

**Comment by cinquemb** [comment]
Hi! No license for it right now. What are you trying to do and what license would you prefer I add?

**Comment by benswift** [comment]
I wanted to (ab)use it to make some experimental noise music, actually. Or at least to try.

I'm an MIT type of guy usually, so that would make it easy. But obviously it's your call :)

**Comment by cinquemb** [comment]
Sounds pretty cool!

Done: https://github.com/cinquemb/WienerFilter/commit/688b6f455e10764b644cca222c2136ed8f4cbf9a

**Comment by benswift** [comment]
thanks :)
